### ISSUE TITLE
Preview videos not playing

### ISSUE THREAD

**Issue by BirdSamuel** [TheLogicMaster/SDH-AnimationChanger#24]
Kind of an odd error, a friend showed me the plugin + I happily downloaded it. When they clicked on any startup video it would load + play immediately, my preview videos don't seem to load + play at all. The thumbnail gets placed on the webm video, but it never proceeds after.

I can watch preview videos on the official Steam store, and my friend and I compared our Steamdeck settings to no avail. If I can provide any logs or current config I'd be happy to if you could point me in the right direction.

I did check `/tmp/animation_changer.log`, and only saw a few lines initializing, had an initial http error retrieving the store itself (timeout/reach request took a little long) then it initialized. 

I can download/install/see the videos perfectly, but not being able to preview them is a little annoying.

**Comment by TheLogicMaster** [comment]
Hi, both of the above issues should be fixed whenever the next plugin update gets released.

**Comment by BirdSamuel** [comment]
That's great! Thanks a ton for the quick response.
