### ISSUE TITLE
Error managing animations

### ISSUE THREAD

**Issue by sudoreaper** [TheLogicMaster/SDH-AnimationChanger#29]
When trying to manage animations and selecting an option, an error message pops up with a blurry overlay. You can nearly make out there is an error and you need to refresh but there is no way to do so. Also the blurry overlay cannot be closed unless you restart steam deck or switch to desktop and then back. 

At one point I went into a game selection and could make out that there was a js react error 130

what I’ve tried :
1.) reboot from steam and desktop mode
2.) multiple versions of decky loader
3.) restore to factory settings for deck 

any suggestions? 
![image](https://user-images.githubusercontent.com/58519989/206934084-4ef2e836-0ef0-47a5-8464-1425f203d1d9.jpg)

**Comment by TheLogicMaster** [comment]
Presumably this is on the latest preview or beta SteamOS version? A recent update broke dialogs, so hopefully an update to the Decky frontend library can fix it.

**Comment by tschudenizer** [comment]
Hi,
I have the same issue with the Animation Changer module in Decky-Loader and I am also on
the SteamOS / Steam Preview channel. Looking forward to seeing this fixed, is this something that is broken in the
Decky-Loader software/library (or is something wrong within Steam or SteamOS)?
Kind regards,
       Tschudenizer

**Comment by TheLogicMaster** [comment]
Fixed in 1.2.2
