### ISSUE TITLE
Plugin not loading up properly on holoiso(custom name) + decky

### ISSUE THREAD

**Issue by mkikets99** [TheLogicMaster/SDH-AnimationChanger#36]
So... i am using a Anbernic Win600 with holoiso distro...
I updated pathes in main.py file, but it is still looks like something is missing... 
![20230307_221306.jpg](https://user-images.githubusercontent.com/22869811/223541575-76237885-b056-482e-bfc4-623aea064e8f.jpg)

In log file it says that it is initialized...
What missed?

**Comment by TheLogicMaster** [comment]
All of the plugins need to be updated after a recent Steam OS update, which should fix the menu.

**Comment by mkikets99** [comment]
Nope. All plugins are working fine except this one...
Having only those ones:
 - SDH-FreeGames (Working fine, no error, latest version [1.0.1])
 - SDH-CssLoader (Working fine, no error, latest version [1.5.2])
 - SDH-AnimationChanger (Initialized, menu broken, latest version [1.2.3])
 - protondb-decky (Working fine, no error, latest version [1.0.9])
 
What can be?

**Comment by z3razerviper** [comment]
I am having the same issue

**Comment by TheLogicMaster** [comment]
Fixed with latest update

**Comment by mkikets99** [comment]
Yep. It's working now.
Thanks.
