### ISSUE TITLE
'Default' option broken when deck_startup.webm selected in Steam settings

### ISSUE THREAD

**Issue by asiefert** [TheLogicMaster/SDH-AnimationChanger#44]
I'm honestly not sure if this is a SteamOS/client bug or plugin bug, but I figured I might as well post it here just in case.

**SteamOS version**: 3.4.8, latest stable client release. 

**Operating Mode**: Game mode, handheld, no peripherals plugged in

**What I expected to happen**: After selecting Default as the startup video in Animation Changer settings, I expected either the default video to be played (or not at all) when the device is suspended and woken up, after which point the Steam homescreen should show up normally without any user interaction.

**What actually happened**: The Default option being selected in Animation Changer settings while deck_startup.webm is selected in Steam settings is causing the screen to remain blank after suspending and waking the device. The backlight remains on but no picture is shown, until a button press is made. Buttons I've tested so far are ABXY, QAM, and the Steam button.

**How to reproduce**: 
1. Install the plugin and download any startup video.
2. Change the startup video to anything except 'Default' as a control.
4. Change the selection of startup videos in Steam settings to deck_startup.webm and turn on "Use as wake movie" 
5. Suspend and wake up the device via power button, it should play the video and return to the home screen as expected.
6. Open QAM and access Animation changer settings
7. Change the selection for 'Startup' to 'Default'.
8. Suspend and wake up the device via power button.
9. The above problem should occur.

**Steps taken to attempt to resolve issue**:
- Reloading plugin
- Re-installing plugin via Decky menu

None of the above steps have worked unfortunately, so here's hoping that it's solvable on your side and not a deeper steamOS/client bug.

**Comment by TheLogicMaster** [comment]
Doesn't sound like an issue with the plugin. The plugin has the same effect as manually copying animations into the override directory, and deletes them when you set it to default. Before, you had to reboot for it to take effect. This is probably the behavior when you have deck_startup.webm selected in settings but the file gets removed by the plugin.

**Comment by asiefert** [comment]
Closing the issue. Unfortunately it is a steamOS/client bug that persists after a factory reset. It seems to be related to the infinite loading glitch that was supposedly patched in the latest client update. It also affects the status bar and makes it disappear after suspending and resuming. I'll file a bug report over on the steam deck forums.
Cheers!
