### ISSUE TITLE
Boot Animations Not Working

### ISSUE THREAD

**Issue by Bothecat123** [TheLogicMaster/SDH-AnimationChanger#46]
For some reason, it seems like boot animations are defaulting to only showing the suspend animations OR not playing anything at all upon startup. I have everything set to default in the customization settings and I’m not having any luck. It seems like I’m not the only one with the issue either. Is there a fix? 

Thanks for the help! I appreciate your work on the animation changer. Here is a crab emoji to show you my thanks. 🦀

Reddit with more details on the issue:
https://www.reddit.com/r/SteamDeck/comments/14sgj6t/decky_animation_changer_suspend_videos_are_being/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1

https://www.reddit.com/r/SteamDeck/comments/14qx32w/deck_loaders_animation_changer_suspend_animations/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1

**Comment by TheLogicMaster** [comment]
That's strange. Unless something has broken with the plugin or SteamOS, the plugin symlinks animations into `/home/deck/.steam/root/config/uioverrides/movies`, where they should be picked up automatically by SteamOS. In customization settings, there should be an option that comes up as `deck_startup.webm` which needs to be selected.

**Comment by Bothecat123** [comment]
Just tried switching the startup in the customization settings and it still displays suspend animations instead of startup when turning the device on from sleep mode.

**Comment by Bothecat123** [comment]
![IMG_6178](https://github.com/TheLogicMaster/SDH-AnimationChanger/assets/139028967/ab6acc15-287d-49a2-9a4c-856628488f54)
![IMG_6179](https://github.com/TheLogicMaster/SDH-AnimationChanger/assets/139028967/76f76d2c-5288-447d-954b-e5b117f6169b)

**Comment by Bothecat123** [comment]
Those are the settings I have. I’ve messed around with the shuffle and other settings to no avail. 

Video of the problem: 
https://github.com/TheLogicMaster/SDH-AnimationChanger/assets/139028967/55e6b488-a240-4763-8077-79577cb3eb02

**Comment by TheLogicMaster** [comment]
That `Shuffle Startup Movie` option might be an issue. I don't think it's an issue with the plugin, though, since the video shows in the customization settings.

**Comment by Bothecat123** [comment]
That helps! I toggled the shuffle startup off and left the Use as Wake movie on and it finally gets me a startup movie to play. However, the startup movie won’t shuffle upon boot anymore. The other caveat is that it shows some of the suspend animation before hand with it too. 

It also looks like it isn’t using the default suspend animation listed in the Animation Changer either. 

Could the issue be within the Customization menu Steam added? Think it’s a glitch on their part? Is everything working fine on your Deck?

https://github.com/TheLogicMaster/SDH-AnimationChanger/assets/139028967/abea713f-4b22-4bee-8626-88311dd37dc8

**Comment by TheLogicMaster** [comment]
So long as the videos show up in `/home/deck/.steam/root/config/uioverrides/movies`, everything should be working correctly in the plugin. The shuffling feature in the plugin should work, as far as I know, though it only runs when Steam OS actually starts, so it wouldn't work for suspend animations. Definitely not compatible with the Steam OS shuffle feature, though, since it only knows about the video that the plugin has currently set. I've seen some weird issues with the suspend animation briefly showing, but it should be a Steam OS issue. I'm not completely sure of how the new customization settings mess with suspend animations, but I've been leaving all of those settings default to hopefully keep using the override folder videos rather than the official Steam OS ones.

**Comment by Bothecat123** [comment]
That may be part of the issue. Maybe my deck has been upped to use the Steam OS folders instead of what was created by the plug-in.

Just to confirm and make sure I’m on the same page as you - the shuffle feature only works when you restart the whole entire system via the steam button and “restart?”  NOT when the Deck is suspended and turned back on via the power button?

**Comment by TheLogicMaster** [comment]
Correct, it does not do it when suspending, only when restarting Steam OS, which happens either when powering off completely or restarting just Steam from the power menu. At one point that was a planned feature, but there didn't seem to be a reliable way to pick up on that event.

**Comment by Bothecat123** [comment]
Great!

I think I got your suggestion has it fixed for me then. I “thought” I remembered it shuffling after suspended; but, I guess that was wrong. 

Regardless, the “shuffle startup” was definitely the problem behind startup videos not playing. 

Thanks!
