### ISSUE TITLE
List in addon is empty, when clicking on randomize it goes blank. 

### ISSUE THREAD

**Issue by GarnetSunset** [TheLogicMaster/SDH-AnimationChanger#6]
Only option is "current" despite 8 webms in the correct folder! 
![aweew](https://user-images.githubusercontent.com/13430434/195200834-20d2a5d3-fd1a-4d42-8689-75b7ea57159c.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/13430434/195200838-389ce05d-6502-4293-8abb-66ad507184d6.jpg)

**Comment by TheLogicMaster** [comment]
Hi, in the animations directory, it looks for sub-directories with the name of the animation as you want it to show up in the UI. In said sub-directory, it expects to find webm files with names corresponding to the official movie override names, unless you add a config.json file to customize this behavior, as specified in the README.

**Comment by GarnetSunset** [comment]
Oooh thank you!! :)
